# Generated by Django 5.0.7 on 2024-08-19 11:58

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teller',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to=settings.AUTH_USER_MODEL)),
                ('teller_id', models.AutoField(primary_key=True, serialize=False)),
                ('teller_num', models.IntegerField(max_length=45)),
                ('teller_type', models.CharField(max_length=45)),
                ('teller_username', models.CharField(max_length=45, unique=True)),
                ('teller_password', models.CharField(max_length=45, unique=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Voice',
            fields=[
                ('voice_id', models.AutoField(primary_key=True, serialize=False)),
                ('voice_name', models.CharField(max_length=45)),
                ('voice_file', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('client_num', models.IntegerField()),
                ('client_date', models.DateField(auto_now_add=True)),
                ('client_time', models.TimeField(auto_now_add=True)),
                ('client_type', models.CharField(max_length=45)),
                ('client_teller_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.teller')),
            ],
        ),
    ]
