# Generated by Django 5.0.7 on 2024-08-24 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_audio',
            field=models.BooleanField(default=False),
        ),
    ]
