# Generated by Django 5.1 on 2024-08-20 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teller',
            old_name='teller_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='teller',
            old_name='teller_num',
            new_name='num',
        ),
        migrations.RenameField(
            model_name='teller',
            old_name='teller_type',
            new_name='type',
        ),
    ]
