# Generated by Django 5.0.7 on 2024-08-09 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_client_client_teller_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teller',
            name='teller_num',
        ),
    ]
