# Generated by Django 5.0.7 on 2024-08-24 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_client_client_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_teller_id',
            field=models.IntegerField(null=True),
        ),
    ]
