# Generated by Django 5.0.7 on 2024-08-09 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_teller_teller_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
