# Generated by Django 5.0.7 on 2024-08-24 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_client_client_teller_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='client_teller_id',
        ),
        migrations.AddField(
            model_name='client',
            name='client_served',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
