# Generated by Django 5.0.7 on 2024-08-09 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_client_client_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
