# Generated by Django 5.0.7 on 2024-08-10 23:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_client_client_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='client_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
