# Generated by Django 5.0.7 on 2024-08-10 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_client_client_time_alter_client_client_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_date',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_time',
            field=models.CharField(max_length=45),
        ),
    ]
