# Generated by Django 5.0.7 on 2024-08-11 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_client_client_date_alter_client_client_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
