###
#Test Register Endpoint
POST http://127.0.0.1:8000/api/teller/register/
Content-Type: application/json

{
    "username": "maha",
    "password": "maha123",
    "type": "خزنة", 
    "num": 2
}

###
#Test Login Endpoint
POST http://127.0.0.1:8000/api/teller/login/
Content-Type: application/json

{
  "username": "lance",
  "password": "lance123"
}

###
#Test Refresh Endpoint
POST http://127.0.0.1:8000/api/teller/login/refresh
Content-Type: application/json

{
  "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTcyNDQ1MDk5MSwiaWF0IjoxNzI0MzY0NTkxLCJqdGkiOiJkY2YyY2ZjZGE5NmM0YzA1OTFjZTg4ZGYxNGY3OWZiZiIsInVzZXJfaWQiOjJ9.mrKuLcAZpMFPp4kwtsAw4M5Ap1W_ofjtvchDleeMtdE"
}
###
#Test Token Endpoint
GET http://127.0.0.1:8000/api/teller/test_token/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzI0MjA0NzIyLCJpYXQiOjE3MjQyMDQ0MjIsImp0aSI6IjFjZTUzZWQzOWU2YjRiMDg4Y2ZmMzM3YTIxMjBjODBmIiwidXNlcl9pZCI6NX0.BS-Whxi-Cs5oy6WxXAnE89-9TjhQy9v2IwCBeHbPcJk

{

}