###
#Test Register Endpoint
POST http://127.0.0.1:8000/api/teller/register/
Content-Type: application/json

{
    "username": "Safe_3",
    "password": "Moheb_aziz",
    "teller_type": "خزنة", 
    "teller_num": 4
}

###
#Test Login Endpoint
POST http://127.0.0.1:8000/api/teller/login/
Content-Type: application/json

{
  "username": "Safe_3",
  "password": "Safe_3@123"
}

###
#Test Token Endpoint
GET http://127.0.0.1:8000/api/teller/test_token/
Content-Type: application/json
Authorization: Token f9ca36f514b55bdcb715b1aeacddc86d981c4dfc

{

}